// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: portal.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/logic/sysdictitemservice"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/svc"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/pb"
)

type SysDictItemServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSysDictItemServiceServer
}

func NewSysDictItemServiceServer(svcCtx *svc.ServiceContext) *SysDictItemServiceServer {
	return &SysDictItemServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------字典数据表-----------------------
func (s *SysDictItemServiceServer) AddSysDictItem(ctx context.Context, in *pb.AddSysDictItemReq) (*pb.AddSysDictItemResp, error) {
	l := sysdictitemservicelogic.NewAddSysDictItemLogic(ctx, s.svcCtx)
	return l.AddSysDictItem(in)
}

func (s *SysDictItemServiceServer) UpdateSysDictItem(ctx context.Context, in *pb.UpdateSysDictItemReq) (*pb.UpdateSysDictItemResp, error) {
	l := sysdictitemservicelogic.NewUpdateSysDictItemLogic(ctx, s.svcCtx)
	return l.UpdateSysDictItem(in)
}

func (s *SysDictItemServiceServer) DelSysDictItem(ctx context.Context, in *pb.DelSysDictItemReq) (*pb.DelSysDictItemResp, error) {
	l := sysdictitemservicelogic.NewDelSysDictItemLogic(ctx, s.svcCtx)
	return l.DelSysDictItem(in)
}

func (s *SysDictItemServiceServer) GetSysDictItemById(ctx context.Context, in *pb.GetSysDictItemByIdReq) (*pb.GetSysDictItemByIdResp, error) {
	l := sysdictitemservicelogic.NewGetSysDictItemByIdLogic(ctx, s.svcCtx)
	return l.GetSysDictItemById(in)
}

func (s *SysDictItemServiceServer) SearchSysDictItem(ctx context.Context, in *pb.SearchSysDictItemReq) (*pb.SearchSysDictItemResp, error) {
	l := sysdictitemservicelogic.NewSearchSysDictItemLogic(ctx, s.svcCtx)
	return l.SearchSysDictItem(in)
}

func (s *SysDictItemServiceServer) CheckDictItemCode(ctx context.Context, in *pb.CheckDictItemCodeReq) (*pb.CheckDictItemCodeResp, error) {
	l := sysdictitemservicelogic.NewCheckDictItemCodeLogic(ctx, s.svcCtx)
	return l.CheckDictItemCode(in)
}

func (s *SysDictItemServiceServer) GetDictItemText(ctx context.Context, in *pb.GetDictItemNameReq) (*pb.GetDictItemTextResp, error) {
	l := sysdictitemservicelogic.NewGetDictItemTextLogic(ctx, s.svcCtx)
	return l.GetDictItemText(in)
}
