// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecNodeFieldNames          = builder.RawFieldNames(&OnecNode{})
	onecNodeRows                = strings.Join(onecNodeFieldNames, ",")
	onecNodeRowsExpectAutoSet   = strings.Join(stringx.Remove(onecNodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecNodeRowsWithPlaceHolder = strings.Join(stringx.Remove(onecNodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeOnecOnecNodeIdPrefix                  = "cache:kubeOnec:onecNode:id:"
	cacheKubeOnecOnecNodeClusterUuidNodeNamePrefix = "cache:kubeOnec:onecNode:clusterUuid:nodeName:"
	cacheKubeOnecOnecNodeNodeUidPrefix             = "cache:kubeOnec:onecNode:nodeUid:"
)

type (
	onecNodeModel interface {
		Insert(ctx context.Context, data *OnecNode) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*OnecNode, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecNode, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecNode, error)
		FindOneByClusterUuidNodeName(ctx context.Context, clusterUuid string, nodeName string) (*OnecNode, error)
		FindOneByNodeUid(ctx context.Context, nodeUid string) (*OnecNode, error)
		Update(ctx context.Context, data *OnecNode) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecNodeModel struct {
		sqlc.CachedConn
		table string
	}

	OnecNode struct {
		Id               uint64    `db:"id"`                // 自增主键
		ClusterUuid      string    `db:"cluster_uuid"`      // 所属集群ID
		NodeName         string    `db:"node_name"`         // 节点名称，在同一集群中唯一
		Cpu              int64     `db:"cpu"`               // CPU核数
		Memory           float64   `db:"memory"`            // 内存大小，Mi
		MaxPods          int64     `db:"max_pods"`          // 最大Pod数量
		IsGpu            int64     `db:"is_gpu"`            // 节点是否包含GPU
		NodeUid          string    `db:"node_uid"`          // 节点UID，唯一标识
		Status           string    `db:"status"`            // 节点状态
		SyncStatus       int64     `db:"sync_status"`       // 节点同步状态
		Roles            string    `db:"roles"`             // 节点角色列表
		JoinAt           time.Time `db:"join_at"`           // 节点加入集群时间
		PodCidr          string    `db:"pod_cidr"`          // Pod CIDR
		Unschedulable    int64     `db:"unschedulable"`     // 节点是否不可调度（0：可调度，1：不可调度）
		NodeIp           string    `db:"node_ip"`           // 节点地址
		Os               string    `db:"os"`                // 操作系统
		KernelVersion    string    `db:"kernel_version"`    // 内核版本
		ContainerRuntime string    `db:"container_runtime"` // 容器运行时
		KubeletVersion   string    `db:"kubelet_version"`   // Kubelet版本
		KubeletPort      uint64    `db:"kubelet_port"`      // Kubelet端口号
		OperatingSystem  string    `db:"operating_system"`  // 操作系统类型
		Architecture     string    `db:"architecture"`      // 架构类型
		CreatedBy        string    `db:"created_by"`        // 记录创建人
		UpdatedBy        string    `db:"updated_by"`        // 记录更新人
		CreatedAt        time.Time `db:"created_at"`        // 记录创建时间
		UpdatedAt        time.Time `db:"updated_at"`        // 记录更新时间
		IsDeleted        int64     `db:"is_deleted"`        // 是否删除
	}
)

func newOnecNodeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecNodeModel {
	return &defaultOnecNodeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_node`",
	}
}

func (m *defaultOnecNodeModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeOnecOnecNodeClusterUuidNodeNameKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecNodeClusterUuidNodeNamePrefix, data.ClusterUuid, data.NodeName)
	kubeOnecOnecNodeIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeIdPrefix, id)
	kubeOnecOnecNodeNodeUidKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeNodeUidPrefix, data.NodeUid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecOnecNodeClusterUuidNodeNameKey, kubeOnecOnecNodeIdKey, kubeOnecOnecNodeNodeUidKey)
	return err
}

func (m *defaultOnecNodeModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeOnecOnecNodeClusterUuidNodeNameKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecNodeClusterUuidNodeNamePrefix, data.ClusterUuid, data.NodeName)
	kubeOnecOnecNodeIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeIdPrefix, id)
	kubeOnecOnecNodeNodeUidKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeNodeUidPrefix, data.NodeUid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecOnecNodeClusterUuidNodeNameKey, kubeOnecOnecNodeIdKey, kubeOnecOnecNodeNodeUidKey)
	return err
}

func (m *defaultOnecNodeModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecNodeModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		kubeOnecOnecNodeClusterUuidNodeNameKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecNodeClusterUuidNodeNamePrefix, data.ClusterUuid, data.NodeName)
		kubeOnecOnecNodeIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeIdPrefix, id)
		kubeOnecOnecNodeNodeUidKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeNodeUidPrefix, data.NodeUid) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeOnecOnecNodeClusterUuidNodeNameKey, kubeOnecOnecNodeIdKey, kubeOnecOnecNodeNodeUidKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultOnecNodeModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		kubeOnecOnecNodeClusterUuidNodeNameKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecNodeClusterUuidNodeNamePrefix, data.ClusterUuid, data.NodeName)
		kubeOnecOnecNodeIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeIdPrefix, id)
		kubeOnecOnecNodeNodeUidKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeNodeUidPrefix, data.NodeUid) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeOnecOnecNodeClusterUuidNodeNameKey, kubeOnecOnecNodeIdKey, kubeOnecOnecNodeNodeUidKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultOnecNodeModel) FindOne(ctx context.Context, id uint64) (*OnecNode, error) {
	kubeOnecOnecNodeIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeIdPrefix, id)
	var resp OnecNode
	err := m.QueryRowCtx(ctx, &resp, kubeOnecOnecNodeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecNodeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecNodeModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecNode, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecNode
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecNodeRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecNodeModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecNode, error) {
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecNodeRows, m.table, where, orderStr)
	var resp []*OnecNode
	err := m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultOnecNodeModel) FindOneByClusterUuidNodeName(ctx context.Context, clusterUuid string, nodeName string) (*OnecNode, error) {
	kubeOnecOnecNodeClusterUuidNodeNameKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecNodeClusterUuidNodeNamePrefix, clusterUuid, nodeName)
	var resp OnecNode
	err := m.QueryRowIndexCtx(ctx, &resp, kubeOnecOnecNodeClusterUuidNodeNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `cluster_uuid` = ? and `node_name` = ? AND `is_deleted` = 0  limit 1", onecNodeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, clusterUuid, nodeName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecNodeModel) FindOneByNodeUid(ctx context.Context, nodeUid string) (*OnecNode, error) {
	kubeOnecOnecNodeNodeUidKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeNodeUidPrefix, nodeUid)
	var resp OnecNode
	err := m.QueryRowIndexCtx(ctx, &resp, kubeOnecOnecNodeNodeUidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `node_uid` = ? AND `is_deleted` = 0  limit 1", onecNodeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, nodeUid); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecNodeModel) Insert(ctx context.Context, data *OnecNode) (sql.Result, error) {
	kubeOnecOnecNodeClusterUuidNodeNameKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecNodeClusterUuidNodeNamePrefix, data.ClusterUuid, data.NodeName)
	kubeOnecOnecNodeIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeIdPrefix, data.Id)
	kubeOnecOnecNodeNodeUidKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeNodeUidPrefix, data.NodeUid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecNodeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ClusterUuid, data.NodeName, data.Cpu, data.Memory, data.MaxPods, data.IsGpu, data.NodeUid, data.Status, data.SyncStatus, data.Roles, data.JoinAt, data.PodCidr, data.Unschedulable, data.NodeIp, data.Os, data.KernelVersion, data.ContainerRuntime, data.KubeletVersion, data.KubeletPort, data.OperatingSystem, data.Architecture, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeOnecOnecNodeClusterUuidNodeNameKey, kubeOnecOnecNodeIdKey, kubeOnecOnecNodeNodeUidKey)
	return ret, err
}

func (m *defaultOnecNodeModel) Update(ctx context.Context, newData *OnecNode) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeOnecOnecNodeClusterUuidNodeNameKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecNodeClusterUuidNodeNamePrefix, data.ClusterUuid, data.NodeName)
	kubeOnecOnecNodeIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeIdPrefix, data.Id)
	kubeOnecOnecNodeNodeUidKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeNodeUidPrefix, data.NodeUid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecNodeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ClusterUuid, newData.NodeName, newData.Cpu, newData.Memory, newData.MaxPods, newData.IsGpu, newData.NodeUid, newData.Status, newData.SyncStatus, newData.Roles, newData.JoinAt, newData.PodCidr, newData.Unschedulable, newData.NodeIp, newData.Os, newData.KernelVersion, newData.ContainerRuntime, newData.KubeletVersion, newData.KubeletPort, newData.OperatingSystem, newData.Architecture, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, kubeOnecOnecNodeClusterUuidNodeNameKey, kubeOnecOnecNodeIdKey, kubeOnecOnecNodeNodeUidKey)
	return err
}

func (m *defaultOnecNodeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeOnecOnecNodeIdPrefix, primary)
}

func (m *defaultOnecNodeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecNodeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecNodeModel) tableName() string {
	return m.table
}
