// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecClusterConnInfoFieldNames          = builder.RawFieldNames(&OnecClusterConnInfo{})
	onecClusterConnInfoRows                = strings.Join(onecClusterConnInfoFieldNames, ",")
	onecClusterConnInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(onecClusterConnInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecClusterConnInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(onecClusterConnInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeOnecOnecClusterConnInfoIdPrefix                     = "cache:kubeOnec:onecClusterConnInfo:id:"
	cacheKubeOnecOnecClusterConnInfoClusterUuidServiceCodePrefix = "cache:kubeOnec:onecClusterConnInfo:clusterUuid:serviceCode:"
)

type (
	onecClusterConnInfoModel interface {
		Insert(ctx context.Context, data *OnecClusterConnInfo) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*OnecClusterConnInfo, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecClusterConnInfo, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecClusterConnInfo, error)
		FindOneByClusterUuidServiceCode(ctx context.Context, clusterUuid string, serviceCode string) (*OnecClusterConnInfo, error)
		Update(ctx context.Context, data *OnecClusterConnInfo) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecClusterConnInfoModel struct {
		sqlc.CachedConn
		table string
	}

	OnecClusterConnInfo struct {
		Id           uint64         `db:"id"`            // 自增主键
		ClusterUuid  string         `db:"cluster_uuid"`  // 关联集群 ID（唯一标识集群）
		ServiceCode  string         `db:"service_code"`  // 服务编码（唯一标识服务）
		ServiceUrl   string         `db:"service_url"`   // 服务的 URL
		Username     string         `db:"username"`      // 用户名（用于基本认证）
		Password     string         `db:"password"`      // 密码（用于基本认证）
		Token        string         `db:"token"`         // 令牌（用于 Token 认证）
		SkipInsecure int64          `db:"skip_insecure"` // 是否跳过自签名证书验证（0-否，1-是）
		CaCert       sql.NullString `db:"ca_cert"`       // CA 证书内容（PEM 格式）
		ClientCert   sql.NullString `db:"client_cert"`   // 客户端证书内容（PEM 格式）
		ClientKey    sql.NullString `db:"client_key"`    // 客户端私钥内容（PEM 格式，仅客户端证书需要）
		CreatedBy    string         `db:"created_by"`    // 记录创建人
		UpdatedBy    string         `db:"updated_by"`    // 记录更新人
		CreatedAt    time.Time      `db:"created_at"`    // 记录创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 记录更新时间
		IsDeleted    int64          `db:"is_deleted"`    // 是否删除
	}
)

func newOnecClusterConnInfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecClusterConnInfoModel {
	return &defaultOnecClusterConnInfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_cluster_conn_info`",
	}
}

func (m *defaultOnecClusterConnInfoModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecClusterConnInfoClusterUuidServiceCodePrefix, data.ClusterUuid, data.ServiceCode)
	kubeOnecOnecClusterConnInfoIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecClusterConnInfoIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey, kubeOnecOnecClusterConnInfoIdKey)
	return err
}

func (m *defaultOnecClusterConnInfoModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecClusterConnInfoClusterUuidServiceCodePrefix, data.ClusterUuid, data.ServiceCode)
	kubeOnecOnecClusterConnInfoIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecClusterConnInfoIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey, kubeOnecOnecClusterConnInfoIdKey)
	return err
}

func (m *defaultOnecClusterConnInfoModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecClusterConnInfoModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecClusterConnInfoClusterUuidServiceCodePrefix, data.ClusterUuid, data.ServiceCode)
		kubeOnecOnecClusterConnInfoIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecClusterConnInfoIdPrefix, id) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey, kubeOnecOnecClusterConnInfoIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultOnecClusterConnInfoModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecClusterConnInfoClusterUuidServiceCodePrefix, data.ClusterUuid, data.ServiceCode)
		kubeOnecOnecClusterConnInfoIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecClusterConnInfoIdPrefix, id) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey, kubeOnecOnecClusterConnInfoIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultOnecClusterConnInfoModel) FindOne(ctx context.Context, id uint64) (*OnecClusterConnInfo, error) {
	kubeOnecOnecClusterConnInfoIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecClusterConnInfoIdPrefix, id)
	var resp OnecClusterConnInfo
	err := m.QueryRowCtx(ctx, &resp, kubeOnecOnecClusterConnInfoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecClusterConnInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecClusterConnInfoModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecClusterConnInfo, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecClusterConnInfo
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecClusterConnInfoRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecClusterConnInfoModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecClusterConnInfo, error) {
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecClusterConnInfoRows, m.table, where, orderStr)
	var resp []*OnecClusterConnInfo
	err := m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultOnecClusterConnInfoModel) FindOneByClusterUuidServiceCode(ctx context.Context, clusterUuid string, serviceCode string) (*OnecClusterConnInfo, error) {
	kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecClusterConnInfoClusterUuidServiceCodePrefix, clusterUuid, serviceCode)
	var resp OnecClusterConnInfo
	err := m.QueryRowIndexCtx(ctx, &resp, kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `cluster_uuid` = ? and `service_code` = ? AND `is_deleted` = 0  limit 1", onecClusterConnInfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, clusterUuid, serviceCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecClusterConnInfoModel) Insert(ctx context.Context, data *OnecClusterConnInfo) (sql.Result, error) {
	kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecClusterConnInfoClusterUuidServiceCodePrefix, data.ClusterUuid, data.ServiceCode)
	kubeOnecOnecClusterConnInfoIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecClusterConnInfoIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, onecClusterConnInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ClusterUuid, data.ServiceCode, data.ServiceUrl, data.Username, data.Password, data.Token, data.SkipInsecure, data.CaCert, data.ClientCert, data.ClientKey, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey, kubeOnecOnecClusterConnInfoIdKey)
	return ret, err
}

func (m *defaultOnecClusterConnInfoModel) Update(ctx context.Context, newData *OnecClusterConnInfo) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecClusterConnInfoClusterUuidServiceCodePrefix, data.ClusterUuid, data.ServiceCode)
	kubeOnecOnecClusterConnInfoIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecClusterConnInfoIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecClusterConnInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ClusterUuid, newData.ServiceCode, newData.ServiceUrl, newData.Username, newData.Password, newData.Token, newData.SkipInsecure, newData.CaCert, newData.ClientCert, newData.ClientKey, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, kubeOnecOnecClusterConnInfoClusterUuidServiceCodeKey, kubeOnecOnecClusterConnInfoIdKey)
	return err
}

func (m *defaultOnecClusterConnInfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeOnecOnecClusterConnInfoIdPrefix, primary)
}

func (m *defaultOnecClusterConnInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", onecClusterConnInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecClusterConnInfoModel) tableName() string {
	return m.table
}
