// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	onecProjectAdminFieldNames          = builder.RawFieldNames(&OnecProjectAdmin{})
	onecProjectAdminRows                = strings.Join(onecProjectAdminFieldNames, ",")
	onecProjectAdminRowsExpectAutoSet   = strings.Join(stringx.Remove(onecProjectAdminFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	onecProjectAdminRowsWithPlaceHolder = strings.Join(stringx.Remove(onecProjectAdminFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeOnecOnecProjectAdminIdPrefix              = "cache:kubeOnec:onecProjectAdmin:id:"
	cacheKubeOnecOnecProjectAdminProjectIdUserIdPrefix = "cache:kubeOnec:onecProjectAdmin:projectId:userId:"
)

type (
	onecProjectAdminModel interface {
		Insert(ctx context.Context, data *OnecProjectAdmin) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*OnecProjectAdmin, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecProjectAdmin, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecProjectAdmin, error)
		FindOneByProjectIdUserId(ctx context.Context, projectId uint64, userId uint64) (*OnecProjectAdmin, error)
		Update(ctx context.Context, data *OnecProjectAdmin) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultOnecProjectAdminModel struct {
		sqlc.CachedConn
		table string
	}

	OnecProjectAdmin struct {
		Id         uint64       `db:"id"`          // 主键，自增 ID
		ProjectId  uint64       `db:"project_id"`  // 关联的项目 ID
		UserId     uint64       `db:"user_id"`     // 关联的用户 ID
		CreateBy   string       `db:"create_by"`   // 记录创建人
		UpdateBy   string       `db:"update_by"`   // 记录更新人
		CreateTime time.Time    `db:"create_time"` // 记录创建时间
		UpdateTime time.Time    `db:"update_time"` // 记录更新时间
		DeleteTime sql.NullTime `db:"delete_time"` // 记录删除时间（软删除）
	}
)

func newOnecProjectAdminModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOnecProjectAdminModel {
	return &defaultOnecProjectAdminModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`onec_project_admin`",
	}
}

func (m *defaultOnecProjectAdminModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeOnecOnecProjectAdminIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecProjectAdminIdPrefix, id)
	kubeOnecOnecProjectAdminProjectIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecProjectAdminProjectIdUserIdPrefix, data.ProjectId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecOnecProjectAdminIdKey, kubeOnecOnecProjectAdminProjectIdUserIdKey)
	return err
}

func (m *defaultOnecProjectAdminModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.DeleteTime.Valid {
		return nil
	}
	kubeOnecOnecProjectAdminIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecProjectAdminIdPrefix, id)
	kubeOnecOnecProjectAdminProjectIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecProjectAdminProjectIdUserIdPrefix, data.ProjectId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set delete_time = NOW() where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecOnecProjectAdminIdKey, kubeOnecOnecProjectAdminProjectIdUserIdKey)
	return err
}

func (m *defaultOnecProjectAdminModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultOnecProjectAdminModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		kubeOnecOnecProjectAdminIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecProjectAdminIdPrefix, id)
		kubeOnecOnecProjectAdminProjectIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecProjectAdminProjectIdUserIdPrefix, data.ProjectId, data.UserId) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeOnecOnecProjectAdminIdKey, kubeOnecOnecProjectAdminProjectIdUserIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultOnecProjectAdminModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		kubeOnecOnecProjectAdminIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecProjectAdminIdPrefix, id)
		kubeOnecOnecProjectAdminProjectIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecProjectAdminProjectIdUserIdPrefix, data.ProjectId, data.UserId) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeOnecOnecProjectAdminIdKey, kubeOnecOnecProjectAdminProjectIdUserIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultOnecProjectAdminModel) FindOne(ctx context.Context, id uint64) (*OnecProjectAdmin, error) {
	kubeOnecOnecProjectAdminIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecProjectAdminIdPrefix, id)
	var resp OnecProjectAdmin
	err := m.QueryRowCtx(ctx, &resp, kubeOnecOnecProjectAdminIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `delete_time` IS NULL limit 1", onecProjectAdminRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecProjectAdminModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*OnecProjectAdmin, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 delete_time IS NULL 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE delete_time IS NULL"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND delete_time IS NULL", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*OnecProjectAdmin
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", onecProjectAdminRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultOnecProjectAdminModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*OnecProjectAdmin, error) {
	// 初始化 WHERE 子句
	where := "WHERE delete_time IS NULL"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND delete_time IS NULL", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", onecProjectAdminRows, m.table, where, orderStr)
	var resp []*OnecProjectAdmin
	err := m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultOnecProjectAdminModel) FindOneByProjectIdUserId(ctx context.Context, projectId uint64, userId uint64) (*OnecProjectAdmin, error) {
	kubeOnecOnecProjectAdminProjectIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecProjectAdminProjectIdUserIdPrefix, projectId, userId)
	var resp OnecProjectAdmin
	err := m.QueryRowIndexCtx(ctx, &resp, kubeOnecOnecProjectAdminProjectIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `project_id` = ? and `user_id` = ? AND `delete_time` IS NULL limit 1", onecProjectAdminRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, projectId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOnecProjectAdminModel) Insert(ctx context.Context, data *OnecProjectAdmin) (sql.Result, error) {
	kubeOnecOnecProjectAdminIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecProjectAdminIdPrefix, data.Id)
	kubeOnecOnecProjectAdminProjectIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecProjectAdminProjectIdUserIdPrefix, data.ProjectId, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, onecProjectAdminRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProjectId, data.UserId, data.CreateBy, data.UpdateBy, data.DeleteTime)
	}, kubeOnecOnecProjectAdminIdKey, kubeOnecOnecProjectAdminProjectIdUserIdKey)
	return ret, err
}

func (m *defaultOnecProjectAdminModel) Update(ctx context.Context, newData *OnecProjectAdmin) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeOnecOnecProjectAdminIdKey := fmt.Sprintf("%s%v", cacheKubeOnecOnecProjectAdminIdPrefix, data.Id)
	kubeOnecOnecProjectAdminProjectIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecOnecProjectAdminProjectIdUserIdPrefix, data.ProjectId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, onecProjectAdminRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ProjectId, newData.UserId, newData.CreateBy, newData.UpdateBy, newData.DeleteTime, newData.Id)
	}, kubeOnecOnecProjectAdminIdKey, kubeOnecOnecProjectAdminProjectIdUserIdKey)
	return err
}

func (m *defaultOnecProjectAdminModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeOnecOnecProjectAdminIdPrefix, primary)
}

func (m *defaultOnecProjectAdminModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `delete_time` IS NULL limit 1", onecProjectAdminRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOnecProjectAdminModel) tableName() string {
	return m.table
}
