// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	cluster "github.com/yanshicheng/kube-onec/application/manager/api/internal/handler/cluster"
	node "github.com/yanshicheng/kube-onec/application/manager/api/internal/handler/node"
	"github.com/yanshicheng/kube-onec/application/manager/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: cluster.AddOnecClusterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: cluster.SearchOnecClusterHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: cluster.UpdateOnecClusterHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: cluster.DelOnecClusterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: cluster.GetOnecClusterByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nodes",
					Handler: cluster.AddOnecNodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/sync/:id",
					Handler: cluster.SyncOnecClusterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/onec/manager/cluster"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: cluster.AddOnecClusterConnInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: cluster.SearchOnecClusterConnInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: cluster.UpdateOnecClusterConnInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: cluster.DelOnecClusterConnInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: cluster.GetOnecClusterConnInfoByIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/onec/manager/cluster/conn-info"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: node.SearchOnecNodeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: node.DelOnecNodeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: node.GetOnecNodeByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/annotations",
					Handler: node.AddOnecNodeAnnotationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/annotations",
					Handler: node.SearchOnecNodeAnnotationHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/annotations/:id",
					Handler: node.DelOnecNodeAnnotationHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/disable/:id",
					Handler: node.ForbidScheduledNodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/enable/:id",
					Handler: node.EnableScheduledNodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/evict/:id",
					Handler: node.EvictOnecNodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/labels",
					Handler: node.AddOnecNodeLabelHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/labels",
					Handler: node.SearchOnecNodeLabelHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/labels/:id",
					Handler: node.DelOnecNodeLabelHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/sync/:id",
					Handler: node.SyncOnecNodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/taints",
					Handler: node.AddOnecNodeTaintHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/taints",
					Handler: node.SearchOnecNodeTaintHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/taints/:id",
					Handler: node.DelOnecNodeTaintHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/onec/manager/node"),
	)
}
