// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: manager.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-onec/application/manager/rpc/internal/logic/onecclusterconninfoservice"
	"github.com/yanshicheng/kube-onec/application/manager/rpc/internal/svc"
	"github.com/yanshicheng/kube-onec/application/manager/rpc/pb"
)

type OnecClusterConnInfoServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOnecClusterConnInfoServiceServer
}

func NewOnecClusterConnInfoServiceServer(svcCtx *svc.ServiceContext) *OnecClusterConnInfoServiceServer {
	return &OnecClusterConnInfoServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------通用的服务连接信息表，动态支持多个服务-----------------------
func (s *OnecClusterConnInfoServiceServer) AddOnecClusterConnInfo(ctx context.Context, in *pb.AddOnecClusterConnInfoReq) (*pb.AddOnecClusterConnInfoResp, error) {
	l := onecclusterconninfoservicelogic.NewAddOnecClusterConnInfoLogic(ctx, s.svcCtx)
	return l.AddOnecClusterConnInfo(in)
}

func (s *OnecClusterConnInfoServiceServer) UpdateOnecClusterConnInfo(ctx context.Context, in *pb.UpdateOnecClusterConnInfoReq) (*pb.UpdateOnecClusterConnInfoResp, error) {
	l := onecclusterconninfoservicelogic.NewUpdateOnecClusterConnInfoLogic(ctx, s.svcCtx)
	return l.UpdateOnecClusterConnInfo(in)
}

func (s *OnecClusterConnInfoServiceServer) DelOnecClusterConnInfo(ctx context.Context, in *pb.DelOnecClusterConnInfoReq) (*pb.DelOnecClusterConnInfoResp, error) {
	l := onecclusterconninfoservicelogic.NewDelOnecClusterConnInfoLogic(ctx, s.svcCtx)
	return l.DelOnecClusterConnInfo(in)
}

func (s *OnecClusterConnInfoServiceServer) GetOnecClusterConnInfoById(ctx context.Context, in *pb.GetOnecClusterConnInfoByIdReq) (*pb.GetOnecClusterConnInfoByIdResp, error) {
	l := onecclusterconninfoservicelogic.NewGetOnecClusterConnInfoByIdLogic(ctx, s.svcCtx)
	return l.GetOnecClusterConnInfoById(in)
}

func (s *OnecClusterConnInfoServiceServer) SearchOnecClusterConnInfo(ctx context.Context, in *pb.SearchOnecClusterConnInfoReq) (*pb.SearchOnecClusterConnInfoResp, error) {
	l := onecclusterconninfoservicelogic.NewSearchOnecClusterConnInfoLogic(ctx, s.svcCtx)
	return l.SearchOnecClusterConnInfo(in)
}
