// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: manager.proto

package onecprojectadminservice

import (
	"context"

	"github.com/yanshicheng/kube-onec/application/manager/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddOnecClusterConnInfoReq         = pb.AddOnecClusterConnInfoReq
	AddOnecClusterConnInfoResp        = pb.AddOnecClusterConnInfoResp
	AddOnecClusterReq                 = pb.AddOnecClusterReq
	AddOnecClusterResp                = pb.AddOnecClusterResp
	AddOnecNodeAnnotationReq          = pb.AddOnecNodeAnnotationReq
	AddOnecNodeAnnotationResp         = pb.AddOnecNodeAnnotationResp
	AddOnecNodeLabelReq               = pb.AddOnecNodeLabelReq
	AddOnecNodeLabelResp              = pb.AddOnecNodeLabelResp
	AddOnecNodeReq                    = pb.AddOnecNodeReq
	AddOnecNodeResp                   = pb.AddOnecNodeResp
	AddOnecNodeTaintReq               = pb.AddOnecNodeTaintReq
	AddOnecNodeTaintResp              = pb.AddOnecNodeTaintResp
	AddOnecProjectAdminReq            = pb.AddOnecProjectAdminReq
	AddOnecProjectAdminResp           = pb.AddOnecProjectAdminResp
	AddOnecProjectApplicationReq      = pb.AddOnecProjectApplicationReq
	AddOnecProjectApplicationResp     = pb.AddOnecProjectApplicationResp
	AddOnecProjectQuotaReq            = pb.AddOnecProjectQuotaReq
	AddOnecProjectQuotaResp           = pb.AddOnecProjectQuotaResp
	AddOnecProjectReq                 = pb.AddOnecProjectReq
	AddOnecProjectResp                = pb.AddOnecProjectResp
	CancelForbidOnecNodeReq           = pb.CancelForbidOnecNodeReq
	CancelForbidOnecNodeResp          = pb.CancelForbidOnecNodeResp
	DelOnecClusterConnInfoReq         = pb.DelOnecClusterConnInfoReq
	DelOnecClusterConnInfoResp        = pb.DelOnecClusterConnInfoResp
	DelOnecClusterReq                 = pb.DelOnecClusterReq
	DelOnecClusterResp                = pb.DelOnecClusterResp
	DelOnecNodeAnnotationReq          = pb.DelOnecNodeAnnotationReq
	DelOnecNodeAnnotationResp         = pb.DelOnecNodeAnnotationResp
	DelOnecNodeLabelReq               = pb.DelOnecNodeLabelReq
	DelOnecNodeLabelResp              = pb.DelOnecNodeLabelResp
	DelOnecNodeReq                    = pb.DelOnecNodeReq
	DelOnecNodeResp                   = pb.DelOnecNodeResp
	DelOnecNodeTaintReq               = pb.DelOnecNodeTaintReq
	DelOnecNodeTaintResp              = pb.DelOnecNodeTaintResp
	DelOnecProjectAdminReq            = pb.DelOnecProjectAdminReq
	DelOnecProjectAdminResp           = pb.DelOnecProjectAdminResp
	DelOnecProjectApplicationReq      = pb.DelOnecProjectApplicationReq
	DelOnecProjectApplicationResp     = pb.DelOnecProjectApplicationResp
	DelOnecProjectQuotaReq            = pb.DelOnecProjectQuotaReq
	DelOnecProjectQuotaResp           = pb.DelOnecProjectQuotaResp
	DelOnecProjectReq                 = pb.DelOnecProjectReq
	DelOnecProjectResp                = pb.DelOnecProjectResp
	ForbidOnecNodeReq                 = pb.ForbidOnecNodeReq
	ForbidOnecNodeResp                = pb.ForbidOnecNodeResp
	GetOnecClusterByIdReq             = pb.GetOnecClusterByIdReq
	GetOnecClusterByIdResp            = pb.GetOnecClusterByIdResp
	GetOnecClusterConnInfoByIdReq     = pb.GetOnecClusterConnInfoByIdReq
	GetOnecClusterConnInfoByIdResp    = pb.GetOnecClusterConnInfoByIdResp
	GetOnecNodeByIdReq                = pb.GetOnecNodeByIdReq
	GetOnecNodeByIdResp               = pb.GetOnecNodeByIdResp
	GetOnecProjectAdminByIdReq        = pb.GetOnecProjectAdminByIdReq
	GetOnecProjectAdminByIdResp       = pb.GetOnecProjectAdminByIdResp
	GetOnecProjectApplicationByIdReq  = pb.GetOnecProjectApplicationByIdReq
	GetOnecProjectApplicationByIdResp = pb.GetOnecProjectApplicationByIdResp
	GetOnecProjectByIdReq             = pb.GetOnecProjectByIdReq
	GetOnecProjectByIdResp            = pb.GetOnecProjectByIdResp
	GetOnecProjectQuotaByIdReq        = pb.GetOnecProjectQuotaByIdReq
	GetOnecProjectQuotaByIdResp       = pb.GetOnecProjectQuotaByIdResp
	OnecCluster                       = pb.OnecCluster
	OnecClusterConnInfo               = pb.OnecClusterConnInfo
	OnecNode                          = pb.OnecNode
	OnecProject                       = pb.OnecProject
	OnecProjectAdmin                  = pb.OnecProjectAdmin
	OnecProjectApplication            = pb.OnecProjectApplication
	OnecProjectQuota                  = pb.OnecProjectQuota
	SearchOnecClusterConnInfoReq      = pb.SearchOnecClusterConnInfoReq
	SearchOnecClusterConnInfoResp     = pb.SearchOnecClusterConnInfoResp
	SearchOnecClusterReq              = pb.SearchOnecClusterReq
	SearchOnecClusterResp             = pb.SearchOnecClusterResp
	SearchOnecNodeReq                 = pb.SearchOnecNodeReq
	SearchOnecNodeResp                = pb.SearchOnecNodeResp
	SearchOnecProjectAdminReq         = pb.SearchOnecProjectAdminReq
	SearchOnecProjectAdminResp        = pb.SearchOnecProjectAdminResp
	SearchOnecProjectApplicationReq   = pb.SearchOnecProjectApplicationReq
	SearchOnecProjectApplicationResp  = pb.SearchOnecProjectApplicationResp
	SearchOnecProjectQuotaReq         = pb.SearchOnecProjectQuotaReq
	SearchOnecProjectQuotaResp        = pb.SearchOnecProjectQuotaResp
	SearchOnecProjectReq              = pb.SearchOnecProjectReq
	SearchOnecProjectResp             = pb.SearchOnecProjectResp
	SyncOnecClusterReq                = pb.SyncOnecClusterReq
	SyncOnecClusterResp               = pb.SyncOnecClusterResp
	SyncOnecNodeReq                   = pb.SyncOnecNodeReq
	SyncOnecNodeResp                  = pb.SyncOnecNodeResp
	UpdateOnecClusterConnInfoReq      = pb.UpdateOnecClusterConnInfoReq
	UpdateOnecClusterConnInfoResp     = pb.UpdateOnecClusterConnInfoResp
	UpdateOnecClusterReq              = pb.UpdateOnecClusterReq
	UpdateOnecClusterResp             = pb.UpdateOnecClusterResp
	UpdateOnecProjectAdminReq         = pb.UpdateOnecProjectAdminReq
	UpdateOnecProjectAdminResp        = pb.UpdateOnecProjectAdminResp
	UpdateOnecProjectApplicationReq   = pb.UpdateOnecProjectApplicationReq
	UpdateOnecProjectApplicationResp  = pb.UpdateOnecProjectApplicationResp
	UpdateOnecProjectQuotaReq         = pb.UpdateOnecProjectQuotaReq
	UpdateOnecProjectQuotaResp        = pb.UpdateOnecProjectQuotaResp
	UpdateOnecProjectReq              = pb.UpdateOnecProjectReq
	UpdateOnecProjectResp             = pb.UpdateOnecProjectResp

	OnecProjectAdminService interface {
		// -----------------------项目管理员表，关联项目与用户的多对多关系-----------------------
		AddOnecProjectAdmin(ctx context.Context, in *AddOnecProjectAdminReq, opts ...grpc.CallOption) (*AddOnecProjectAdminResp, error)
		UpdateOnecProjectAdmin(ctx context.Context, in *UpdateOnecProjectAdminReq, opts ...grpc.CallOption) (*UpdateOnecProjectAdminResp, error)
		DelOnecProjectAdmin(ctx context.Context, in *DelOnecProjectAdminReq, opts ...grpc.CallOption) (*DelOnecProjectAdminResp, error)
		GetOnecProjectAdminById(ctx context.Context, in *GetOnecProjectAdminByIdReq, opts ...grpc.CallOption) (*GetOnecProjectAdminByIdResp, error)
		SearchOnecProjectAdmin(ctx context.Context, in *SearchOnecProjectAdminReq, opts ...grpc.CallOption) (*SearchOnecProjectAdminResp, error)
	}

	defaultOnecProjectAdminService struct {
		cli zrpc.Client
	}
)

func NewOnecProjectAdminService(cli zrpc.Client) OnecProjectAdminService {
	return &defaultOnecProjectAdminService{
		cli: cli,
	}
}

// -----------------------项目管理员表，关联项目与用户的多对多关系-----------------------
func (m *defaultOnecProjectAdminService) AddOnecProjectAdmin(ctx context.Context, in *AddOnecProjectAdminReq, opts ...grpc.CallOption) (*AddOnecProjectAdminResp, error) {
	client := pb.NewOnecProjectAdminServiceClient(m.cli.Conn())
	return client.AddOnecProjectAdmin(ctx, in, opts...)
}

func (m *defaultOnecProjectAdminService) UpdateOnecProjectAdmin(ctx context.Context, in *UpdateOnecProjectAdminReq, opts ...grpc.CallOption) (*UpdateOnecProjectAdminResp, error) {
	client := pb.NewOnecProjectAdminServiceClient(m.cli.Conn())
	return client.UpdateOnecProjectAdmin(ctx, in, opts...)
}

func (m *defaultOnecProjectAdminService) DelOnecProjectAdmin(ctx context.Context, in *DelOnecProjectAdminReq, opts ...grpc.CallOption) (*DelOnecProjectAdminResp, error) {
	client := pb.NewOnecProjectAdminServiceClient(m.cli.Conn())
	return client.DelOnecProjectAdmin(ctx, in, opts...)
}

func (m *defaultOnecProjectAdminService) GetOnecProjectAdminById(ctx context.Context, in *GetOnecProjectAdminByIdReq, opts ...grpc.CallOption) (*GetOnecProjectAdminByIdResp, error) {
	client := pb.NewOnecProjectAdminServiceClient(m.cli.Conn())
	return client.GetOnecProjectAdminById(ctx, in, opts...)
}

func (m *defaultOnecProjectAdminService) SearchOnecProjectAdmin(ctx context.Context, in *SearchOnecProjectAdminReq, opts ...grpc.CallOption) (*SearchOnecProjectAdminResp, error) {
	client := pb.NewOnecProjectAdminServiceClient(m.cli.Conn())
	return client.SearchOnecProjectAdmin(ctx, in, opts...)
}
