// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictItemFieldNames          = builder.RawFieldNames(&SysDictItem{})
	sysDictItemRows                = strings.Join(sysDictItemFieldNames, ",")
	sysDictItemRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysDictItemRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDictItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeOnecSysDictItemIdPrefix               = "cache:kubeOnec:sysDictItem:id:"
	cacheKubeOnecSysDictItemDictCodeItemCodePrefix = "cache:kubeOnec:sysDictItem:dictCode:itemCode:"
	cacheKubeOnecSysDictItemItemCodePrefix         = "cache:kubeOnec:sysDictItem:itemCode:"
)

type (
	sysDictItemModel interface {
		Insert(ctx context.Context, data *SysDictItem) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*SysDictItem, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysDictItem, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysDictItem, error)
		FindOneByDictCodeItemCode(ctx context.Context, dictCode string, itemCode string) (*SysDictItem, error)
		FindOneByItemCode(ctx context.Context, itemCode string) (*SysDictItem, error)
		Update(ctx context.Context, data *SysDictItem) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultSysDictItemModel struct {
		sqlc.CachedConn
		table string
	}

	SysDictItem struct {
		Id          uint64       `db:"id"`          // 自增主键
		DictCode    string       `db:"dict_code"`   // 字典code，
		ItemText    string       `db:"item_text"`   // 字典项文本
		ItemCode    string       `db:"item_code"`   // 字典项值
		Description string       `db:"description"` // 描述
		SortOrder   int64        `db:"sort_order"`  // 排序
		CreateBy    string       `db:"create_by"`   // 创建人
		UpdateBy    string       `db:"update_by"`   // 更新人
		CreateTime  time.Time    `db:"create_time"` // 创建时间
		UpdateTime  time.Time    `db:"update_time"` // 最后修改时间
		DeleteTime  sql.NullTime `db:"delete_time"` // 记录删除时间（NULL表示未删除）
	}
)

func newSysDictItemModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysDictItemModel {
	return &defaultSysDictItemModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_dict_item`",
	}
}

func (m *defaultSysDictItemModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeOnecSysDictItemDictCodeItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysDictItemDictCodeItemCodePrefix, data.DictCode, data.ItemCode)
	kubeOnecSysDictItemIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemIdPrefix, id)
	kubeOnecSysDictItemItemCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemItemCodePrefix, data.ItemCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecSysDictItemDictCodeItemCodeKey, kubeOnecSysDictItemIdKey, kubeOnecSysDictItemItemCodeKey)
	return err
}

func (m *defaultSysDictItemModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.DeleteTime.Valid {
		return nil
	}
	kubeOnecSysDictItemDictCodeItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysDictItemDictCodeItemCodePrefix, data.DictCode, data.ItemCode)
	kubeOnecSysDictItemIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemIdPrefix, id)
	kubeOnecSysDictItemItemCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemItemCodePrefix, data.ItemCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set delete_time = NOW() where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecSysDictItemDictCodeItemCodeKey, kubeOnecSysDictItemIdKey, kubeOnecSysDictItemItemCodeKey)
	return err
}

func (m *defaultSysDictItemModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultSysDictItemModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		kubeOnecSysDictItemDictCodeItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysDictItemDictCodeItemCodePrefix, data.DictCode, data.ItemCode)
		kubeOnecSysDictItemIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemIdPrefix, id)
		kubeOnecSysDictItemItemCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemItemCodePrefix, data.ItemCode) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeOnecSysDictItemDictCodeItemCodeKey, kubeOnecSysDictItemIdKey, kubeOnecSysDictItemItemCodeKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultSysDictItemModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		kubeOnecSysDictItemDictCodeItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysDictItemDictCodeItemCodePrefix, data.DictCode, data.ItemCode)
		kubeOnecSysDictItemIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemIdPrefix, id)
		kubeOnecSysDictItemItemCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemItemCodePrefix, data.ItemCode) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeOnecSysDictItemDictCodeItemCodeKey, kubeOnecSysDictItemIdKey, kubeOnecSysDictItemItemCodeKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultSysDictItemModel) FindOne(ctx context.Context, id uint64) (*SysDictItem, error) {
	kubeOnecSysDictItemIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemIdPrefix, id)
	var resp SysDictItem
	err := m.QueryRowCtx(ctx, &resp, kubeOnecSysDictItemIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `delete_time` IS NULL limit 1", sysDictItemRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictItemModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysDictItem, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 delete_time IS NULL 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE delete_time IS NULL"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND delete_time IS NULL", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*SysDictItem
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", sysDictItemRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultSysDictItemModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysDictItem, error) {
	// 初始化 WHERE 子句
	where := "WHERE delete_time IS NULL"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND delete_time IS NULL", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", sysDictItemRows, m.table, where, orderStr)
	var resp []*SysDictItem
	err := m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultSysDictItemModel) FindOneByDictCodeItemCode(ctx context.Context, dictCode string, itemCode string) (*SysDictItem, error) {
	kubeOnecSysDictItemDictCodeItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysDictItemDictCodeItemCodePrefix, dictCode, itemCode)
	var resp SysDictItem
	err := m.QueryRowIndexCtx(ctx, &resp, kubeOnecSysDictItemDictCodeItemCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `dict_code` = ? and `item_code` = ? AND `delete_time` IS NULL limit 1", sysDictItemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, dictCode, itemCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictItemModel) FindOneByItemCode(ctx context.Context, itemCode string) (*SysDictItem, error) {
	kubeOnecSysDictItemItemCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemItemCodePrefix, itemCode)
	var resp SysDictItem
	err := m.QueryRowIndexCtx(ctx, &resp, kubeOnecSysDictItemItemCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `item_code` = ? AND `delete_time` IS NULL limit 1", sysDictItemRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, itemCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictItemModel) Insert(ctx context.Context, data *SysDictItem) (sql.Result, error) {
	kubeOnecSysDictItemDictCodeItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysDictItemDictCodeItemCodePrefix, data.DictCode, data.ItemCode)
	kubeOnecSysDictItemIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemIdPrefix, data.Id)
	kubeOnecSysDictItemItemCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemItemCodePrefix, data.ItemCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysDictItemRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DictCode, data.ItemText, data.ItemCode, data.Description, data.SortOrder, data.CreateBy, data.UpdateBy, data.DeleteTime)
	}, kubeOnecSysDictItemDictCodeItemCodeKey, kubeOnecSysDictItemIdKey, kubeOnecSysDictItemItemCodeKey)
	return ret, err
}

func (m *defaultSysDictItemModel) Update(ctx context.Context, newData *SysDictItem) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeOnecSysDictItemDictCodeItemCodeKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysDictItemDictCodeItemCodePrefix, data.DictCode, data.ItemCode)
	kubeOnecSysDictItemIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemIdPrefix, data.Id)
	kubeOnecSysDictItemItemCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemItemCodePrefix, data.ItemCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysDictItemRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DictCode, newData.ItemText, newData.ItemCode, newData.Description, newData.SortOrder, newData.CreateBy, newData.UpdateBy, newData.DeleteTime, newData.Id)
	}, kubeOnecSysDictItemDictCodeItemCodeKey, kubeOnecSysDictItemIdKey, kubeOnecSysDictItemItemCodeKey)
	return err
}

func (m *defaultSysDictItemModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeOnecSysDictItemIdPrefix, primary)
}

func (m *defaultSysDictItemModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `delete_time` IS NULL limit 1", sysDictItemRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysDictItemModel) tableName() string {
	return m.table
}
