// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictFieldNames          = builder.RawFieldNames(&SysDict{})
	sysDictRows                = strings.Join(sysDictFieldNames, ",")
	sysDictRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysDictRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDictFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeOnecSysDictIdPrefix       = "cache:kubeOnec:sysDict:id:"
	cacheKubeOnecSysDictDictCodePrefix = "cache:kubeOnec:sysDict:dictCode:"
)

type (
	sysDictModel interface {
		Insert(ctx context.Context, data *SysDict) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*SysDict, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysDict, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysDict, error)
		FindOneByDictCode(ctx context.Context, dictCode string) (*SysDict, error)
		Update(ctx context.Context, data *SysDict) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultSysDictModel struct {
		sqlc.CachedConn
		table string
	}

	SysDict struct {
		Id          uint64    `db:"id"`          // 自增主键
		DictName    string    `db:"dict_name"`   // 字典名称
		DictCode    string    `db:"dict_code"`   // 字典编码
		Description string    `db:"description"` // 描述
		CreatedBy   string    `db:"created_by"`  // 创建者
		UpdatedBy   string    `db:"updated_by"`  // 更新者
		CreatedAt   time.Time `db:"created_at"`  // 记录创建时间
		UpdatedAt   time.Time `db:"updated_at"`  // 记录更新时间
		IsDeleted   int64     `db:"is_deleted"`  // 是否删除
	}
)

func newSysDictModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysDictModel {
	return &defaultSysDictModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_dict`",
	}
}

func (m *defaultSysDictModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeOnecSysDictDictCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictDictCodePrefix, data.DictCode)
	kubeOnecSysDictIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecSysDictDictCodeKey, kubeOnecSysDictIdKey)
	return err
}

func (m *defaultSysDictModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeOnecSysDictDictCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictDictCodePrefix, data.DictCode)
	kubeOnecSysDictIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecSysDictDictCodeKey, kubeOnecSysDictIdKey)
	return err
}

func (m *defaultSysDictModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultSysDictModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		kubeOnecSysDictDictCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictDictCodePrefix, data.DictCode)
		kubeOnecSysDictIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictIdPrefix, id) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeOnecSysDictDictCodeKey, kubeOnecSysDictIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultSysDictModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		kubeOnecSysDictDictCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictDictCodePrefix, data.DictCode)
		kubeOnecSysDictIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictIdPrefix, id) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeOnecSysDictDictCodeKey, kubeOnecSysDictIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultSysDictModel) FindOne(ctx context.Context, id uint64) (*SysDict, error) {
	kubeOnecSysDictIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictIdPrefix, id)
	var resp SysDict
	err := m.QueryRowCtx(ctx, &resp, kubeOnecSysDictIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", sysDictRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysDict, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*SysDict
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", sysDictRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultSysDictModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysDict, error) {
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", sysDictRows, m.table, where, orderStr)
	var resp []*SysDict
	err := m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultSysDictModel) FindOneByDictCode(ctx context.Context, dictCode string) (*SysDict, error) {
	kubeOnecSysDictDictCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictDictCodePrefix, dictCode)
	var resp SysDict
	err := m.QueryRowIndexCtx(ctx, &resp, kubeOnecSysDictDictCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `dict_code` = ? AND `is_deleted` = 0  limit 1", sysDictRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, dictCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictModel) Insert(ctx context.Context, data *SysDict) (sql.Result, error) {
	kubeOnecSysDictDictCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictDictCodePrefix, data.DictCode)
	kubeOnecSysDictIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, sysDictRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DictName, data.DictCode, data.Description, data.CreatedBy, data.UpdatedBy, data.IsDeleted)
	}, kubeOnecSysDictDictCodeKey, kubeOnecSysDictIdKey)
	return ret, err
}

func (m *defaultSysDictModel) Update(ctx context.Context, newData *SysDict) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeOnecSysDictDictCodeKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictDictCodePrefix, data.DictCode)
	kubeOnecSysDictIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysDictIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysDictRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DictName, newData.DictCode, newData.Description, newData.CreatedBy, newData.UpdatedBy, newData.IsDeleted, newData.Id)
	}, kubeOnecSysDictDictCodeKey, kubeOnecSysDictIdKey)
	return err
}

func (m *defaultSysDictModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeOnecSysDictIdPrefix, primary)
}

func (m *defaultSysDictModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", sysDictRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysDictModel) tableName() string {
	return m.table
}
