// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysOrganizationFieldNames          = builder.RawFieldNames(&SysOrganization{})
	sysOrganizationRows                = strings.Join(sysOrganizationFieldNames, ",")
	sysOrganizationRowsExpectAutoSet   = strings.Join(stringx.Remove(sysOrganizationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysOrganizationRowsWithPlaceHolder = strings.Join(stringx.Remove(sysOrganizationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeOnecSysOrganizationIdPrefix = "cache:kubeOnec:sysOrganization:id:"
)

type (
	sysOrganizationModel interface {
		Insert(ctx context.Context, data *SysOrganization) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*SysOrganization, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysOrganization, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysOrganization, error)
		Update(ctx context.Context, data *SysOrganization) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultSysOrganizationModel struct {
		sqlc.CachedConn
		table string
	}

	SysOrganization struct {
		Id          uint64       `db:"id"`          // 自增主键
		Name        string       `db:"name"`        // 团队名称
		ParentId    uint64       `db:"parent_id"`   // 父级组织的 ID，根级为 NULL
		Level       int64        `db:"level"`       // 组织层级，从 0 开始
		Description string       `db:"description"` // 组织描述
		CreateTime  time.Time    `db:"create_time"` // 创建时间
		UpdateTime  time.Time    `db:"update_time"` // 最后修改时间
		DeleteTime  sql.NullTime `db:"delete_time"` // 记录删除时间（为 NULL 表示未删除）
	}
)

func newSysOrganizationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysOrganizationModel {
	return &defaultSysOrganizationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_organization`",
	}
}

func (m *defaultSysOrganizationModel) Delete(ctx context.Context, id uint64) error {
	kubeOnecSysOrganizationIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysOrganizationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecSysOrganizationIdKey)
	return err
}

func (m *defaultSysOrganizationModel) DeleteSoft(ctx context.Context, id uint64) error {
	kubeOnecSysOrganizationIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysOrganizationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set delete_time = NOW() where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecSysOrganizationIdKey)
	return err
}

func (m *defaultSysOrganizationModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultSysOrganizationModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）

		// 缓存相关处理

		kubeOnecSysOrganizationIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysOrganizationIdPrefix, id) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeOnecSysOrganizationIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultSysOrganizationModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）

		kubeOnecSysOrganizationIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysOrganizationIdPrefix, id) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeOnecSysOrganizationIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultSysOrganizationModel) FindOne(ctx context.Context, id uint64) (*SysOrganization, error) {
	kubeOnecSysOrganizationIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysOrganizationIdPrefix, id)
	var resp SysOrganization
	err := m.QueryRowCtx(ctx, &resp, kubeOnecSysOrganizationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `delete_time` IS NULL limit 1", sysOrganizationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysOrganizationModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysOrganization, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 delete_time IS NULL 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE delete_time IS NULL"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND delete_time IS NULL", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*SysOrganization
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", sysOrganizationRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultSysOrganizationModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysOrganization, error) {
	// 初始化 WHERE 子句
	where := "WHERE delete_time IS NULL"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND delete_time IS NULL", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", sysOrganizationRows, m.table, where, orderStr)
	var resp []*SysOrganization
	err := m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysOrganizationModel) Insert(ctx context.Context, data *SysOrganization) (sql.Result, error) {
	kubeOnecSysOrganizationIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysOrganizationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, sysOrganizationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.ParentId, data.Level, data.Description, data.DeleteTime)
	}, kubeOnecSysOrganizationIdKey)
	return ret, err
}

func (m *defaultSysOrganizationModel) Update(ctx context.Context, data *SysOrganization) error {
	kubeOnecSysOrganizationIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysOrganizationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysOrganizationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.ParentId, data.Level, data.Description, data.DeleteTime, data.Id)
	}, kubeOnecSysOrganizationIdKey)
	return err
}

func (m *defaultSysOrganizationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeOnecSysOrganizationIdPrefix, primary)
}

func (m *defaultSysOrganizationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `delete_time` IS NULL limit 1", sysOrganizationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysOrganizationModel) tableName() string {
	return m.table
}
