// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUserRoleFieldNames          = builder.RawFieldNames(&SysUserRole{})
	sysUserRoleRows                = strings.Join(sysUserRoleFieldNames, ",")
	sysUserRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(sysUserRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysUserRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(sysUserRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheKubeOnecSysUserRoleIdPrefix           = "cache:kubeOnec:sysUserRole:id:"
	cacheKubeOnecSysUserRoleUserIdRoleIdPrefix = "cache:kubeOnec:sysUserRole:userId:roleId:"
)

type (
	sysUserRoleModel interface {
		Insert(ctx context.Context, data *SysUserRole) (sql.Result, error)

		FindOne(ctx context.Context, id uint64) (*SysUserRole, error)
		Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysUserRole, uint64, error)
		SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysUserRole, error)
		FindOneByUserIdRoleId(ctx context.Context, userId uint64, roleId uint64) (*SysUserRole, error)
		Update(ctx context.Context, data *SysUserRole) error
		Delete(ctx context.Context, id uint64) error
		DeleteSoft(ctx context.Context, id uint64) error
		TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
		TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error)
		ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error)
	}

	defaultSysUserRoleModel struct {
		sqlc.CachedConn
		table string
	}

	SysUserRole struct {
		Id        uint64    `db:"id"`         // 自增主键
		UserId    uint64    `db:"user_id"`    // 用户ID，关联 sys_user 表
		RoleId    uint64    `db:"role_id"`    // 角色ID，关联 sys_role 表
		CreatedAt time.Time `db:"created_at"` // 记录创建时间
		UpdatedAt time.Time `db:"updated_at"` // 记录更新时间
		IsDeleted int64     `db:"is_deleted"` // 是否删除
	}
)

func newSysUserRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysUserRoleModel {
	return &defaultSysUserRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_user_role`",
	}
}

func (m *defaultSysUserRoleModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	kubeOnecSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysUserRoleIdPrefix, id)
	kubeOnecSysUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecSysUserRoleIdKey, kubeOnecSysUserRoleUserIdRoleIdKey)
	return err
}

func (m *defaultSysUserRoleModel) DeleteSoft(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	// 如果记录已软删除，无需再次删除
	if data.IsDeleted == 1 {
		return nil
	}
	kubeOnecSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysUserRoleIdPrefix, id)
	kubeOnecSysUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = 1 where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, kubeOnecSysUserRoleIdKey, kubeOnecSysUserRoleUserIdRoleIdKey)
	return err
}

func (m *defaultSysUserRoleModel) TransCtx(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultSysUserRoleModel) TransOnSql(ctx context.Context, session sqlx.Session, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	// 如果 id != 0 并且启用了缓存逻辑
	if !isZeroValue(id) {
		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		// 缓存相关处理

		kubeOnecSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysUserRoleIdPrefix, id)
		kubeOnecSysUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return session.ExecCtx(ctx, query, args...)
		}, kubeOnecSysUserRoleIdKey, kubeOnecSysUserRoleUserIdRoleIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return session.ExecCtx(ctx, query, args...)
	})
}

func (m *defaultSysUserRoleModel) ExecSql(ctx context.Context, id uint64, sqlStr string, args ...any) (sql.Result, error) {
	// 如果 id != 0 并且启用了缓存逻辑
	query := strings.ReplaceAll(sqlStr, "{table}", m.table)
	if !isZeroValue(id) {
		// 缓存相关处理

		// 查询数据（如果需要，确保数据存在）
		data, err := m.FindOne(ctx, id)
		if err != nil {
			return nil, err
		}

		kubeOnecSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysUserRoleIdPrefix, id)
		kubeOnecSysUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId) // 处理缓存逻辑，例如删除或更新缓存
		// 执行带缓存处理的 SQL 操作
		return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
			return conn.ExecCtx(ctx, query, args...)
		}, kubeOnecSysUserRoleIdKey, kubeOnecSysUserRoleUserIdRoleIdKey) // 传递缓存相关的键值

	}

	// 如果 id == 0 或不需要缓存，直接执行 SQL
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		return conn.ExecCtx(ctx, query, args...)
	})
}
func (m *defaultSysUserRoleModel) FindOne(ctx context.Context, id uint64) (*SysUserRole, error) {
	kubeOnecSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysUserRoleIdPrefix, id)
	var resp SysUserRole
	err := m.QueryRowCtx(ctx, &resp, kubeOnecSysUserRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", sysUserRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserRoleModel) Search(ctx context.Context, orderStr string, isAsc bool, page, pageSize uint64, queryStr string, args ...any) ([]*SysUserRole, uint64, error) {
	// 确保分页参数有效
	if page < 1 {
		page = 1
	}
	if pageSize < 1 {
		pageSize = 20
	}

	// 构造查询条件
	// 添加 `is_deleted` = 0 条件，保证只查询未软删除数据
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}

	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}

	countQuery := fmt.Sprintf("SELECT COUNT(1) FROM %s %s", m.table, where)

	var total uint64
	var resp []*SysUserRole
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	if total == 0 {
		// 无匹配记录
		return resp, 0, ErrNotFound
	}
	offset := (page - 1) * pageSize
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT %d,%d", sysUserRoleRows, m.table, where, orderStr, offset, pageSize)

	err = m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *defaultSysUserRoleModel) SearchNoPage(ctx context.Context, orderStr string, isAsc bool, queryStr string, args ...any) ([]*SysUserRole, error) {
	// 初始化 WHERE 子句
	where := "WHERE `is_deleted` = 0"
	if queryStr != "" {
		where = fmt.Sprintf("WHERE %s AND `is_deleted` = 0", queryStr)
	}

	// 根据 isAsc 参数确定排序方式
	sortDirection := "ASC"
	if !isAsc {
		sortDirection = "DESC"
	}
	// 如果用户未指定排序字段，则默认使用 id
	if orderStr == "" {
		orderStr = fmt.Sprintf("ORDER BY id %s", sortDirection)
	} else {
		orderStr = strings.TrimSpace(orderStr)
		if !strings.HasPrefix(strings.ToUpper(orderStr), "ORDER BY") {
			orderStr = "ORDER BY " + orderStr
		}
		orderStr = fmt.Sprintf("%s %s", orderStr, sortDirection)
	}
	dataQuery := fmt.Sprintf("SELECT %s FROM %s %s %s", sysUserRoleRows, m.table, where, orderStr)
	var resp []*SysUserRole
	err := m.QueryRowsNoCacheCtx(ctx, &resp, dataQuery, args...)
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultSysUserRoleModel) FindOneByUserIdRoleId(ctx context.Context, userId uint64, roleId uint64) (*SysUserRole, error) {
	kubeOnecSysUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysUserRoleUserIdRoleIdPrefix, userId, roleId)
	var resp SysUserRole
	err := m.QueryRowIndexCtx(ctx, &resp, kubeOnecSysUserRoleUserIdRoleIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `role_id` = ? AND `is_deleted` = 0  limit 1", sysUserRoleRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, roleId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserRoleModel) Insert(ctx context.Context, data *SysUserRole) (sql.Result, error) {
	kubeOnecSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysUserRoleIdPrefix, data.Id)
	kubeOnecSysUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, sysUserRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId, data.IsDeleted)
	}, kubeOnecSysUserRoleIdKey, kubeOnecSysUserRoleUserIdRoleIdKey)
	return ret, err
}

func (m *defaultSysUserRoleModel) Update(ctx context.Context, newData *SysUserRole) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	kubeOnecSysUserRoleIdKey := fmt.Sprintf("%s%v", cacheKubeOnecSysUserRoleIdPrefix, data.Id)
	kubeOnecSysUserRoleUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheKubeOnecSysUserRoleUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysUserRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.RoleId, newData.IsDeleted, newData.Id)
	}, kubeOnecSysUserRoleIdKey, kubeOnecSysUserRoleUserIdRoleIdKey)
	return err
}

func (m *defaultSysUserRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheKubeOnecSysUserRoleIdPrefix, primary)
}

func (m *defaultSysUserRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND `is_deleted` = 0 limit 1", sysUserRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysUserRoleModel) tableName() string {
	return m.table
}
