// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: manager.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-onec/application/manager/rpc/internal/logic/onecnodeservice"
	"github.com/yanshicheng/kube-onec/application/manager/rpc/internal/svc"
	"github.com/yanshicheng/kube-onec/application/manager/rpc/pb"
)

type OnecNodeServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOnecNodeServiceServer
}

func NewOnecNodeServiceServer(svcCtx *svc.ServiceContext) *OnecNodeServiceServer {
	return &OnecNodeServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------节点表，用于管理各集群中的节点信息-----------------------
func (s *OnecNodeServiceServer) DelOnecNode(ctx context.Context, in *pb.DelOnecNodeReq) (*pb.DelOnecNodeResp, error) {
	l := onecnodeservicelogic.NewDelOnecNodeLogic(ctx, s.svcCtx)
	return l.DelOnecNode(in)
}

func (s *OnecNodeServiceServer) GetOnecNodeById(ctx context.Context, in *pb.GetOnecNodeByIdReq) (*pb.GetOnecNodeByIdResp, error) {
	l := onecnodeservicelogic.NewGetOnecNodeByIdLogic(ctx, s.svcCtx)
	return l.GetOnecNodeById(in)
}

func (s *OnecNodeServiceServer) SearchOnecNode(ctx context.Context, in *pb.SearchOnecNodeReq) (*pb.SearchOnecNodeResp, error) {
	l := onecnodeservicelogic.NewSearchOnecNodeLogic(ctx, s.svcCtx)
	return l.SearchOnecNode(in)
}

// 节点添加标签
func (s *OnecNodeServiceServer) AddOnecNodeLabel(ctx context.Context, in *pb.AddOnecNodeLabelReq) (*pb.AddOnecNodeLabelResp, error) {
	l := onecnodeservicelogic.NewAddOnecNodeLabelLogic(ctx, s.svcCtx)
	return l.AddOnecNodeLabel(in)
}

// 节点删除标签
func (s *OnecNodeServiceServer) DelOnecNodeLabel(ctx context.Context, in *pb.DelOnecNodeLabelReq) (*pb.DelOnecNodeLabelResp, error) {
	l := onecnodeservicelogic.NewDelOnecNodeLabelLogic(ctx, s.svcCtx)
	return l.DelOnecNodeLabel(in)
}

// 节点添加注解
func (s *OnecNodeServiceServer) AddOnecNodeAnnotation(ctx context.Context, in *pb.AddOnecNodeAnnotationReq) (*pb.AddOnecNodeAnnotationResp, error) {
	l := onecnodeservicelogic.NewAddOnecNodeAnnotationLogic(ctx, s.svcCtx)
	return l.AddOnecNodeAnnotation(in)
}

// 节点删除注解
func (s *OnecNodeServiceServer) DelOnecNodeAnnotation(ctx context.Context, in *pb.DelOnecNodeAnnotationReq) (*pb.DelOnecNodeAnnotationResp, error) {
	l := onecnodeservicelogic.NewDelOnecNodeAnnotationLogic(ctx, s.svcCtx)
	return l.DelOnecNodeAnnotation(in)
}

// 禁止调度
func (s *OnecNodeServiceServer) ForbidOnecNode(ctx context.Context, in *pb.ForbidOnecNodeReq) (*pb.ForbidOnecNodeResp, error) {
	l := onecnodeservicelogic.NewForbidOnecNodeLogic(ctx, s.svcCtx)
	return l.ForbidOnecNode(in)
}

// 取消禁止调度
func (s *OnecNodeServiceServer) CancelForbidOnecNode(ctx context.Context, in *pb.CancelForbidOnecNodeReq) (*pb.CancelForbidOnecNodeResp, error) {
	l := onecnodeservicelogic.NewCancelForbidOnecNodeLogic(ctx, s.svcCtx)
	return l.CancelForbidOnecNode(in)
}

// 添加污点
func (s *OnecNodeServiceServer) AddOnecNodeTaint(ctx context.Context, in *pb.AddOnecNodeTaintReq) (*pb.AddOnecNodeTaintResp, error) {
	l := onecnodeservicelogic.NewAddOnecNodeTaintLogic(ctx, s.svcCtx)
	return l.AddOnecNodeTaint(in)
}

// 删除污点
func (s *OnecNodeServiceServer) DelOnecNodeTaint(ctx context.Context, in *pb.DelOnecNodeTaintReq) (*pb.DelOnecNodeTaintResp, error) {
	l := onecnodeservicelogic.NewDelOnecNodeTaintLogic(ctx, s.svcCtx)
	return l.DelOnecNodeTaint(in)
}

// 同步节点信息
func (s *OnecNodeServiceServer) SyncOnecNode(ctx context.Context, in *pb.SyncOnecNodeReq) (*pb.SyncOnecNodeResp, error) {
	l := onecnodeservicelogic.NewSyncOnecNodeLogic(ctx, s.svcCtx)
	return l.SyncOnecNode(in)
}
