// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: portal.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/logic/sysmenuservice"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/svc"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/pb"
)

type SysMenuServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSysMenuServiceServer
}

func NewSysMenuServiceServer(svcCtx *svc.ServiceContext) *SysMenuServiceServer {
	return &SysMenuServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------菜单表-----------------------
func (s *SysMenuServiceServer) AddSysMenu(ctx context.Context, in *pb.AddSysMenuReq) (*pb.AddSysMenuResp, error) {
	l := sysmenuservicelogic.NewAddSysMenuLogic(ctx, s.svcCtx)
	return l.AddSysMenu(in)
}

func (s *SysMenuServiceServer) UpdateSysMenu(ctx context.Context, in *pb.UpdateSysMenuReq) (*pb.UpdateSysMenuResp, error) {
	l := sysmenuservicelogic.NewUpdateSysMenuLogic(ctx, s.svcCtx)
	return l.UpdateSysMenu(in)
}

func (s *SysMenuServiceServer) DelSysMenu(ctx context.Context, in *pb.DelSysMenuReq) (*pb.DelSysMenuResp, error) {
	l := sysmenuservicelogic.NewDelSysMenuLogic(ctx, s.svcCtx)
	return l.DelSysMenu(in)
}

func (s *SysMenuServiceServer) GetSysMenuById(ctx context.Context, in *pb.GetSysMenuByIdReq) (*pb.GetSysMenuByIdResp, error) {
	l := sysmenuservicelogic.NewGetSysMenuByIdLogic(ctx, s.svcCtx)
	return l.GetSysMenuById(in)
}

func (s *SysMenuServiceServer) SearchSysMenu(ctx context.Context, in *pb.SearchSysMenuReq) (*pb.SearchSysMenuResp, error) {
	l := sysmenuservicelogic.NewSearchSysMenuLogic(ctx, s.svcCtx)
	return l.SearchSysMenu(in)
}

// 新增接口：获取菜单树
func (s *SysMenuServiceServer) GetMenuTree(ctx context.Context, in *pb.GetMenuTreeReq) (*pb.GetMenuTreeResp, error) {
	l := sysmenuservicelogic.NewGetMenuTreeLogic(ctx, s.svcCtx)
	return l.GetMenuTree(in)
}
