// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: portal.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/logic/sysdictservice"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/svc"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/pb"
)

type SysDictServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSysDictServiceServer
}

func NewSysDictServiceServer(svcCtx *svc.ServiceContext) *SysDictServiceServer {
	return &SysDictServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------字典表-----------------------
func (s *SysDictServiceServer) AddSysDict(ctx context.Context, in *pb.AddSysDictReq) (*pb.AddSysDictResp, error) {
	l := sysdictservicelogic.NewAddSysDictLogic(ctx, s.svcCtx)
	return l.AddSysDict(in)
}

func (s *SysDictServiceServer) UpdateSysDict(ctx context.Context, in *pb.UpdateSysDictReq) (*pb.UpdateSysDictResp, error) {
	l := sysdictservicelogic.NewUpdateSysDictLogic(ctx, s.svcCtx)
	return l.UpdateSysDict(in)
}

func (s *SysDictServiceServer) DelSysDict(ctx context.Context, in *pb.DelSysDictReq) (*pb.DelSysDictResp, error) {
	l := sysdictservicelogic.NewDelSysDictLogic(ctx, s.svcCtx)
	return l.DelSysDict(in)
}

func (s *SysDictServiceServer) GetSysDictById(ctx context.Context, in *pb.GetSysDictByIdReq) (*pb.GetSysDictByIdResp, error) {
	l := sysdictservicelogic.NewGetSysDictByIdLogic(ctx, s.svcCtx)
	return l.GetSysDictById(in)
}

func (s *SysDictServiceServer) SearchSysDict(ctx context.Context, in *pb.SearchSysDictReq) (*pb.SearchSysDictResp, error) {
	l := sysdictservicelogic.NewSearchSysDictLogic(ctx, s.svcCtx)
	return l.SearchSysDict(in)
}
