// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: manager.proto

package onecprojectapplicationservice

import (
	"context"

	"github.com/yanshicheng/kube-onec/application/manager/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddOnecClusterConnInfoReq         = pb.AddOnecClusterConnInfoReq
	AddOnecClusterConnInfoResp        = pb.AddOnecClusterConnInfoResp
	AddOnecClusterReq                 = pb.AddOnecClusterReq
	AddOnecClusterResp                = pb.AddOnecClusterResp
	AddOnecNodeAnnotationReq          = pb.AddOnecNodeAnnotationReq
	AddOnecNodeAnnotationResp         = pb.AddOnecNodeAnnotationResp
	AddOnecNodeLabelReq               = pb.AddOnecNodeLabelReq
	AddOnecNodeLabelResp              = pb.AddOnecNodeLabelResp
	AddOnecNodeReq                    = pb.AddOnecNodeReq
	AddOnecNodeResp                   = pb.AddOnecNodeResp
	AddOnecNodeTaintReq               = pb.AddOnecNodeTaintReq
	AddOnecNodeTaintResp              = pb.AddOnecNodeTaintResp
	AddOnecProjectAdminReq            = pb.AddOnecProjectAdminReq
	AddOnecProjectAdminResp           = pb.AddOnecProjectAdminResp
	AddOnecProjectApplicationReq      = pb.AddOnecProjectApplicationReq
	AddOnecProjectApplicationResp     = pb.AddOnecProjectApplicationResp
	AddOnecProjectQuotaReq            = pb.AddOnecProjectQuotaReq
	AddOnecProjectQuotaResp           = pb.AddOnecProjectQuotaResp
	AddOnecProjectReq                 = pb.AddOnecProjectReq
	AddOnecProjectResp                = pb.AddOnecProjectResp
	DelOnecClusterConnInfoReq         = pb.DelOnecClusterConnInfoReq
	DelOnecClusterConnInfoResp        = pb.DelOnecClusterConnInfoResp
	DelOnecClusterReq                 = pb.DelOnecClusterReq
	DelOnecClusterResp                = pb.DelOnecClusterResp
	DelOnecNodeAnnotationReq          = pb.DelOnecNodeAnnotationReq
	DelOnecNodeAnnotationResp         = pb.DelOnecNodeAnnotationResp
	DelOnecNodeLabelReq               = pb.DelOnecNodeLabelReq
	DelOnecNodeLabelResp              = pb.DelOnecNodeLabelResp
	DelOnecNodeReq                    = pb.DelOnecNodeReq
	DelOnecNodeResp                   = pb.DelOnecNodeResp
	DelOnecNodeTaintReq               = pb.DelOnecNodeTaintReq
	DelOnecNodeTaintResp              = pb.DelOnecNodeTaintResp
	DelOnecProjectAdminReq            = pb.DelOnecProjectAdminReq
	DelOnecProjectAdminResp           = pb.DelOnecProjectAdminResp
	DelOnecProjectApplicationReq      = pb.DelOnecProjectApplicationReq
	DelOnecProjectApplicationResp     = pb.DelOnecProjectApplicationResp
	DelOnecProjectQuotaReq            = pb.DelOnecProjectQuotaReq
	DelOnecProjectQuotaResp           = pb.DelOnecProjectQuotaResp
	DelOnecProjectReq                 = pb.DelOnecProjectReq
	DelOnecProjectResp                = pb.DelOnecProjectResp
	EnableScheduledNodeReq            = pb.EnableScheduledNodeReq
	EnableScheduledNodeResp           = pb.EnableScheduledNodeResp
	EvictNodePodReq                   = pb.EvictNodePodReq
	EvictNodePodResp                  = pb.EvictNodePodResp
	ForbidScheduledReq                = pb.ForbidScheduledReq
	ForbidScheduledResp               = pb.ForbidScheduledResp
	GetOnecClusterByIdReq             = pb.GetOnecClusterByIdReq
	GetOnecClusterByIdResp            = pb.GetOnecClusterByIdResp
	GetOnecClusterConnInfoByIdReq     = pb.GetOnecClusterConnInfoByIdReq
	GetOnecClusterConnInfoByIdResp    = pb.GetOnecClusterConnInfoByIdResp
	GetOnecNodeByIdReq                = pb.GetOnecNodeByIdReq
	GetOnecNodeByIdResp               = pb.GetOnecNodeByIdResp
	GetOnecProjectAdminByIdReq        = pb.GetOnecProjectAdminByIdReq
	GetOnecProjectAdminByIdResp       = pb.GetOnecProjectAdminByIdResp
	GetOnecProjectApplicationByIdReq  = pb.GetOnecProjectApplicationByIdReq
	GetOnecProjectApplicationByIdResp = pb.GetOnecProjectApplicationByIdResp
	GetOnecProjectByIdReq             = pb.GetOnecProjectByIdReq
	GetOnecProjectByIdResp            = pb.GetOnecProjectByIdResp
	GetOnecProjectQuotaReq            = pb.GetOnecProjectQuotaReq
	GetOnecProjectQuotaResp           = pb.GetOnecProjectQuotaResp
	NodeAnnotations                   = pb.NodeAnnotations
	NodeLabels                        = pb.NodeLabels
	NodeTaints                        = pb.NodeTaints
	OnecCluster                       = pb.OnecCluster
	OnecClusterConnInfo               = pb.OnecClusterConnInfo
	OnecNode                          = pb.OnecNode
	OnecProject                       = pb.OnecProject
	OnecProjectAdmin                  = pb.OnecProjectAdmin
	OnecProjectApplication            = pb.OnecProjectApplication
	OnecProjectQuota                  = pb.OnecProjectQuota
	SearchOnecClusterConnInfoReq      = pb.SearchOnecClusterConnInfoReq
	SearchOnecClusterConnInfoResp     = pb.SearchOnecClusterConnInfoResp
	SearchOnecClusterReq              = pb.SearchOnecClusterReq
	SearchOnecClusterResp             = pb.SearchOnecClusterResp
	SearchOnecNodeAnnotationListReq   = pb.SearchOnecNodeAnnotationListReq
	SearchOnecNodeAnnotationListResp  = pb.SearchOnecNodeAnnotationListResp
	SearchOnecNodeLabelListReq        = pb.SearchOnecNodeLabelListReq
	SearchOnecNodeLabelListResp       = pb.SearchOnecNodeLabelListResp
	SearchOnecNodeReq                 = pb.SearchOnecNodeReq
	SearchOnecNodeResp                = pb.SearchOnecNodeResp
	SearchOnecNodeTaintListReq        = pb.SearchOnecNodeTaintListReq
	SearchOnecNodeTaintListResp       = pb.SearchOnecNodeTaintListResp
	SearchOnecProjectAdminReq         = pb.SearchOnecProjectAdminReq
	SearchOnecProjectAdminResp        = pb.SearchOnecProjectAdminResp
	SearchOnecProjectApplicationReq   = pb.SearchOnecProjectApplicationReq
	SearchOnecProjectApplicationResp  = pb.SearchOnecProjectApplicationResp
	SearchOnecProjectReq              = pb.SearchOnecProjectReq
	SearchOnecProjectResp             = pb.SearchOnecProjectResp
	SyncOnecClusterReq                = pb.SyncOnecClusterReq
	SyncOnecClusterResp               = pb.SyncOnecClusterResp
	SyncOnecNodeReq                   = pb.SyncOnecNodeReq
	SyncOnecNodeResp                  = pb.SyncOnecNodeResp
	UpdateOnecClusterConnInfoReq      = pb.UpdateOnecClusterConnInfoReq
	UpdateOnecClusterConnInfoResp     = pb.UpdateOnecClusterConnInfoResp
	UpdateOnecClusterReq              = pb.UpdateOnecClusterReq
	UpdateOnecClusterResp             = pb.UpdateOnecClusterResp
	UpdateOnecProjectAdminReq         = pb.UpdateOnecProjectAdminReq
	UpdateOnecProjectAdminResp        = pb.UpdateOnecProjectAdminResp
	UpdateOnecProjectApplicationReq   = pb.UpdateOnecProjectApplicationReq
	UpdateOnecProjectApplicationResp  = pb.UpdateOnecProjectApplicationResp
	UpdateOnecProjectQuotaReq         = pb.UpdateOnecProjectQuotaReq
	UpdateOnecProjectQuotaResp        = pb.UpdateOnecProjectQuotaResp
	UpdateOnecProjectReq              = pb.UpdateOnecProjectReq
	UpdateOnecProjectResp             = pb.UpdateOnecProjectResp

	OnecProjectApplicationService interface {
		// -----------------------应用表，-----------------------
		AddOnecProjectApplication(ctx context.Context, in *AddOnecProjectApplicationReq, opts ...grpc.CallOption) (*AddOnecProjectApplicationResp, error)
		UpdateOnecProjectApplication(ctx context.Context, in *UpdateOnecProjectApplicationReq, opts ...grpc.CallOption) (*UpdateOnecProjectApplicationResp, error)
		DelOnecProjectApplication(ctx context.Context, in *DelOnecProjectApplicationReq, opts ...grpc.CallOption) (*DelOnecProjectApplicationResp, error)
		GetOnecProjectApplicationById(ctx context.Context, in *GetOnecProjectApplicationByIdReq, opts ...grpc.CallOption) (*GetOnecProjectApplicationByIdResp, error)
		SearchOnecProjectApplication(ctx context.Context, in *SearchOnecProjectApplicationReq, opts ...grpc.CallOption) (*SearchOnecProjectApplicationResp, error)
	}

	defaultOnecProjectApplicationService struct {
		cli zrpc.Client
	}
)

func NewOnecProjectApplicationService(cli zrpc.Client) OnecProjectApplicationService {
	return &defaultOnecProjectApplicationService{
		cli: cli,
	}
}

// -----------------------应用表，-----------------------
func (m *defaultOnecProjectApplicationService) AddOnecProjectApplication(ctx context.Context, in *AddOnecProjectApplicationReq, opts ...grpc.CallOption) (*AddOnecProjectApplicationResp, error) {
	client := pb.NewOnecProjectApplicationServiceClient(m.cli.Conn())
	return client.AddOnecProjectApplication(ctx, in, opts...)
}

func (m *defaultOnecProjectApplicationService) UpdateOnecProjectApplication(ctx context.Context, in *UpdateOnecProjectApplicationReq, opts ...grpc.CallOption) (*UpdateOnecProjectApplicationResp, error) {
	client := pb.NewOnecProjectApplicationServiceClient(m.cli.Conn())
	return client.UpdateOnecProjectApplication(ctx, in, opts...)
}

func (m *defaultOnecProjectApplicationService) DelOnecProjectApplication(ctx context.Context, in *DelOnecProjectApplicationReq, opts ...grpc.CallOption) (*DelOnecProjectApplicationResp, error) {
	client := pb.NewOnecProjectApplicationServiceClient(m.cli.Conn())
	return client.DelOnecProjectApplication(ctx, in, opts...)
}

func (m *defaultOnecProjectApplicationService) GetOnecProjectApplicationById(ctx context.Context, in *GetOnecProjectApplicationByIdReq, opts ...grpc.CallOption) (*GetOnecProjectApplicationByIdResp, error) {
	client := pb.NewOnecProjectApplicationServiceClient(m.cli.Conn())
	return client.GetOnecProjectApplicationById(ctx, in, opts...)
}

func (m *defaultOnecProjectApplicationService) SearchOnecProjectApplication(ctx context.Context, in *SearchOnecProjectApplicationReq, opts ...grpc.CallOption) (*SearchOnecProjectApplicationResp, error) {
	client := pb.NewOnecProjectApplicationServiceClient(m.cli.Conn())
	return client.SearchOnecProjectApplication(ctx, in, opts...)
}
