// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: portal.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/logic/imageservice"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/svc"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/pb"
)

type ImageServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedImageServiceServer
}

func NewImageServiceServer(svcCtx *svc.ServiceContext) *ImageServiceServer {
	return &ImageServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传图片
func (s *ImageServiceServer) UploadImage(ctx context.Context, in *pb.UploadImageRequest) (*pb.UploadImageResponse, error) {
	l := imageservicelogic.NewUploadImageLogic(ctx, s.svcCtx)
	return l.UploadImage(in)
}
