// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: portal.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/logic/syspositionservice"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/internal/svc"
	"github.com/yanshicheng/kube-onec/application/portal/rpc/pb"
)

type SysPositionServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSysPositionServiceServer
}

func NewSysPositionServiceServer(svcCtx *svc.ServiceContext) *SysPositionServiceServer {
	return &SysPositionServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------职位表-----------------------
func (s *SysPositionServiceServer) AddSysPosition(ctx context.Context, in *pb.AddSysPositionReq) (*pb.AddSysPositionResp, error) {
	l := syspositionservicelogic.NewAddSysPositionLogic(ctx, s.svcCtx)
	return l.AddSysPosition(in)
}

func (s *SysPositionServiceServer) UpdateSysPosition(ctx context.Context, in *pb.UpdateSysPositionReq) (*pb.UpdateSysPositionResp, error) {
	l := syspositionservicelogic.NewUpdateSysPositionLogic(ctx, s.svcCtx)
	return l.UpdateSysPosition(in)
}

func (s *SysPositionServiceServer) DelSysPosition(ctx context.Context, in *pb.DelSysPositionReq) (*pb.DelSysPositionResp, error) {
	l := syspositionservicelogic.NewDelSysPositionLogic(ctx, s.svcCtx)
	return l.DelSysPosition(in)
}

func (s *SysPositionServiceServer) GetSysPositionById(ctx context.Context, in *pb.GetSysPositionByIdReq) (*pb.GetSysPositionByIdResp, error) {
	l := syspositionservicelogic.NewGetSysPositionByIdLogic(ctx, s.svcCtx)
	return l.GetSysPositionById(in)
}

func (s *SysPositionServiceServer) SearchSysPosition(ctx context.Context, in *pb.SearchSysPositionReq) (*pb.SearchSysPositionResp, error) {
	l := syspositionservicelogic.NewSearchSysPositionLogic(ctx, s.svcCtx)
	return l.SearchSysPosition(in)
}

func (s *SysPositionServiceServer) SearchSysPositionByUser(ctx context.Context, in *pb.SearchSysPositionByUserReq) (*pb.SearchSysPositionByUserResp, error) {
	l := syspositionservicelogic.NewSearchSysPositionByUserLogic(ctx, s.svcCtx)
	return l.SearchSysPositionByUser(in)
}
